name: Generate Markdown Files
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running code/generate_md.py"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 pytest jupyter
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run python script (code/generate_md.py)
        run: |
          cd code
          python3 generate_md.py